### PR TITLE
Updated content and images based on feedback

### LINKED ISSUE #89: Update content and images on pages based on feedback
- Values on the About page
- Ensure the header background image for each page is different
- Add OSCA to the partner logos
- Change Our Partners to Partners/Sponsors
- 
- Look through the content update sheet for any content that has been modified and update accordingly

### PR DESCRIPTION
**Pull request by yemisi-o**
- Updated content and icon for Our Values on the About page
- Added seperate header background image for partners page and chapter lead application page
- Added OSCA to the partner logos
- Changed Our Partners to Partners/Sponsors
- Other content modifications as shared

Closes #89

### CODE REVIEW

**Comment by yemisi-o** [comment]
> @yemisi-o thanks for all the clean ups you've been pushing out. 🎉🎉💪
> 
> I have an observation on this, the OSCA logo is bigger than the rest. Is it possible to scale it down a bit so it doesn't appear off?

@mazma1 Thanks, I noticed o, I reduced and tried different options but noticed it was still big because the plugin in use for the slide effect adds the same width to each image inline and this logo is square, unlike the others. I added an inline max-width style to override it which then made it smaller (on my device and browser responsive views I checked).

Can you please send me a screenshot of what it looks like on your screen? I'll explore other options again

**Comment by mazma1** [comment]
> > @yemisi-o thanks for all the clean ups you've been pushing out. tadatadamuscle
> > I have an observation on this, the OSCA logo is bigger than the rest. Is it possible to scale it down a bit so it doesn't appear off?
> 
> @mazma1 Thanks, I noticed o, I reduced and tried different options but noticed it was still big because the plugin in use for the slide effect adds the same width to each image inline and this logo is square, unlike the others. I added an inline max-width style to override it which then made it smaller (on my device and browser responsive views I checked).
> 
> Can you please send me a screenshot of what it looks like on your screen? I'll explore other options again

What it looks like on my phone
Screenshot_20200311-100834

**Comment by yemisi-o** [comment]
@mazma1 thanks. Yes, on desktop, the space is due to the max-width. Resizing the image without trying to maintain aspect ratio is going to distort the image (i.e. make it look stretchy). I will look into alternative solutions as soon as I can

**Comment by yemisi-o** [comment]
@mazma1 Updated

**Pull request merged**
