### PR TITLE
Updated sections in home page and about page

### PR DESCRIPTION
**Pull request by yemisi-o**
Removed the Skills section on about page and replaced it with a community stats section.

image

Removed the founder section on the home page and replaced it with a section of how people can get involved with the community

image

### CODE REVIEW

**Comment by mazma1** [comment]
Last one, the text after "About Us" looks really small for a desktop view:

Screenshot 2020-01-19 at 10 20 56 AM

**Comment by yemisi-o** [comment]
@mazma1 Nice point on 1, I will adjust appropriately. The 'View All Team Members' button was from a merge of a different ticket but I will make the change on this ticket too

As regards the content, it's still dummy text for now. I wouldn't want to make changes for content styling yet until we have the actual content updated.

**Comment by yemisi-o** [comment]
@mazma1 I've updated my PR to address comments 1 and 2

1. 
image

2. 
image

**Comment by mazma1** [comment]
@yemisi-o I don't see this dummy Team Lead on the review app. Is it meant to be there?

**Comment by yemisi-o** [comment]
@mazma1 No. The screenshot is from my local server but it wouldn't be on the deployed version (dynamic content)

**Pull request merged**
