### PR TITLE
Made content of team's page centered and fixed broken partnership's page image

### PR DESCRIPTION
**Pull request by yemisi-o**
- Teams page image and content now centred just like the team section on the About page
- Fixed broken image in production for partnership's page
- Reduced size for some images that were taken too long to load

### CODE REVIEW

**Comment by OdunayoOkebunmi** [comment]
Hi @yemisi-o , I think you missed this. The styles for the texts are different

Screenshot 2020-03-29 at 01 59 48

**Comment by yemisi-o** [comment]
@OdunayoOkebunmi I'm so sorry about my late reply, I somehow missed this comment until Mary brought it to my attention recently. Apologies.

I'm not clear on your feedback, I didn't make changes to text styling or the Partners section in this PR., the partnership page image I fixed is the header image. Can you please clarify? Thank you

**Comment by OdunayoOkebunmi** [comment]
> @OdunayoOkebunmi I'm so sorry about my late reply, I somehow missed this comment until Mary brought it to my attention recently. Apologies.
> 
> I'm not clear on your feedback, I didn't make changes to text styling or the Partners section in this PR., the partnership page image I fixed is the header image. Can you please clarify? Thank you

The 'Partners' text doesn't have the same font color and font weight as the 'Sponsors' text

**Comment by yemisi-o** [comment]
Okay, I will look into this and update appropraitely

**Comment by yemisi-o** [comment]
@OdunayoOkebunmi It took me some time but I understand your feedback clearly now 😅

The different style is the design convention for other headers on the website, the '/' is probably what makes this particular one look odd (you can check the About and Events page for similar headers).

Changing it will make it look different from the other headers (See images below)
image
image

Let me know what you think after taking a look at the other headers across the page

**Pull request merged**
